import { StyleSheet } from "react-native";

export const theme = {
  base: "#24273a",
  mantle: "#1e2030",
  crust: "#181926",
  text: "#cad3f5",
  subtext0: "#a5adcb",
  subtext1: "#b8c0e0",
  surface0: "#363a4f",
  surface1: "#494d64",
  surface2: "#5b6078",
  overlay0: "#6e738d",
  overlay1: "#8087a2",
  overlay2: "#939ab7",
  blue: "#8aadf4",
  lavender: "#b7bdf8",
  sapphire: "#7dc4e4",
  sky: "#91d7e3",
  teal: "#8bd5ca",
  green: "#a6da95",
  yellow: "#eed49f",
  peach: "#f5a97f",
  maroon: "#ee99a0",
  red: "#ed8796",
  mauve: "#c6a0f6",
  pink: "#f5bde6",
  flamingo: "#f0c6c6",
  rosewater: "#f4dbd6",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.base,
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 16,
  },
  mainCharacterContainer: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    maxHeight: "35%",
    width: "100%",
    // marginTop: "5%",
  },
  mainCharacterImage: {
    resizeMode: "contain",
    height: "100%",
    width: "90%",
  },
  stopRecording: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-around",
  },
  answerBox: {
    borderWidth: 2,
    borderColor: theme.surface0,
    borderRadius: 8,
    flex: 1,
    justifyContent: "flex-end",
    width: "95%",
  },
  leevisAnswerText: {
    color: theme.text,
    marginTop: 36,
    marginBottom: 16,
    padding: 8,
    minWidth: "90%",
    maxWidth: "90%",
    minHeight: "20%",
    fontSize: 20,
  },
  clipboardIcon: {
    position: "absolute",
    top: 10,
    left: 15,
    zIndex: 1,
  },
  volumeUpIcon: {
    position: "absolute",
    top: 10,
    right: 15,
    zIndex: 1,
  },
  inputBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "95%",
    paddingVertical: 16,
    paddingHorizontal: 16,
    margin: 8,
    borderWidth: 2,
    borderColor: theme.sky,
    borderRadius: 20,
  },
  inputText: {
    flex: 1,
    fontSize: 15,
    color: theme.text,
    marginHorizontal: 16,
  },
  text: {
    fontSize: 20,
    color: theme.text,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 20,
  },
  button: {
    margin: 16,
    marginHorizontal: 10,
    padding: 16,
    borderRadius: 10,
    backgroundColor: theme.overlay1,
  },
  buttonText: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  icon: {
    position: "absolute",
    top: 0,
    right: 0,
    margin: 16,
    color: theme.overlay0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  spinner: {
    width: 40,
    height: 40,
    borderWidth: 4,
    borderColor: theme.green,
    borderRadius: 20,
    borderTopColor: theme.blue,
    borderLeftColor: theme.blue,
    margin: 10,
  },
});
